### ISSUE TITLE
自定义字体在hadeeth主题失效

### ISSUE THREAD

**Issue by QQQOrange** [mustakshif/Asri-for-SiYuan#11]
使用css实现的自定义字体在其他主题下顺利使用，但是本主题使用不了

**Comment by kokojacket** [comment]
+1

**Comment by mustakshif** [comment]
可以发一下你的CSS代码吗

**Comment by QQQOrange** [comment]
> 找到问题了，下个版本更新。谢谢反馈

@font-face {
font-family: "仓耳今楷01-W03";
font-style: normal;
src: url("plugins/custom-fonts/仓耳今楷01-W03.ttf");
}

:root {
--b3-font-family: "仓耳今楷01-W03", "Helvetica Neue", "Luxi Sans", "DejaVu Sans", "Hiragino Sans GB", "Microsoft Yahei", "sans-serif", "Apple Color Emoji", "Segoe UI Emoji", "Noto Color Emoji", "Segoe UI Symbol", "Android Emoji", "EmojiSymbols";

}

**Comment by mustakshif** [comment]
想继续问一下，是编辑器区域不生效还是所有地方都不生效

**Comment by mustakshif** [comment]
好，是主题字体变量的选择器特殊性太高了。下个版本更新前可以在你的自定义代码中加上 `!important`来让代码生效:
```css

@font-face {
    font-family: "仓耳今楷01-W03";
    font-style: normal;
    src: url("plugins/custom-fonts/仓耳今楷01-W03.ttf");
}

:root {
    --b3-font-family: "仓耳今楷01-W03", "Helvetica Neue", "Luxi Sans", "DejaVu Sans", "Hiragino Sans GB", "Microsoft Yahei", "sans-serif", "Apple Color Emoji", "Segoe UI Emoji", "Noto Color Emoji", "Segoe UI Symbol", "Android Emoji", "EmojiSymbols" !important;

}
```
