### ISSUE TITLE
主菜单是否加框的一个讨论

### ISSUE THREAD

**Issue by xy0124** [mustakshif/Asri-for-SiYuan#15]
![image](https://github.com/mustakshif/Asri-for-SiYuan/assets/99000021/48d29320-400d-40a2-9629-94e56747ee0d)
首先非常喜欢大佬的主题对逻辑和UI的优化，超级喜欢。最新的更新真是让人眼前一亮！
我是从软件打开整体界面来看，从主题整体的设计语言来说，窃以为 主菜单（即我的截图`DailyLife` ）位置，有一个提示的外边框显得有点点不够和谐，如果做到和最右边的功能按钮那样，没有外边框，极简最好，这是纯粹个人一家之言哈。当然，有一个提示性问题，或者是鼠标移动到位置出现一个底色？
第二个就是工作空间这个字体，视觉上感觉上是粗一点，大一点。是不是一样即可？

**Comment by mustakshif** [comment]
谢谢你对主题的认可😊

工作空间按钮的这个设计是借鉴了Safari浏览器相似功能按钮的UI，加框也能与周围元素区分，如下方的「文档树」，加框后就有了是否可点击交互的区别。

底色是有的，鼠标hover后会变成主题色：
<img width="134" alt="image" src="https://github.com/mustakshif/Asri-for-SiYuan/assets/100056458/77c87e99-386b-4fed-a2a8-d275cb7cff22">

字重上我设定的是中粗，但没想到在Windows上看起来这么粗😂，应该是Windows上微软雅黑字体字重区分不够多的缘故。这个后续可能会优化。

如果确实不喜欢边框及粗体，可以使用以下自定义CSS代码：
```css
/*自重调整为普通*/
#toolbar #barWorkspace {
    font-weight: normal;
}

/*边框透明*/
#toolbar #barWorkspace::before{
    outline-color: transparent;
}
```

**Comment by xy0124** [comment]
多谢大佬细心的解答。
Windows平台的一些细节确实做得不够那么好。

**Comment by xy0124** [comment]
![image](https://github.com/mustakshif/Asri-for-SiYuan/assets/99000021/e76e7582-1178-4f8d-bfb3-4bb5c2b4b9d8)
加上之后视觉上看起来舒服多了~哈哈哈哈

**Comment by mustakshif** [comment]
好嘞 喜欢就好哈哈～

预告一下，下个版本改动了工作空间按钮的样式，更新后如果仍需要调整边框和字重得换成以下代码：
```css
#toolbar #barWorkspace {
    font-weight: normal;
    outline-color: transparent;
}
```
